Add database
VitalyKapustin-git/java-filmorate pull request #5
Opened 2022-08-11 23:02 UTC by VitalyKapustin-git

done with DB HW

2022-08-12 19:19 UTC, ddddemo1984 requested changes

2022-08-12 19:19 UTC, ddddemo1984 commented on src/test/java/ru/yandex/practicum/filmorate/FilmorateApplicationTests.java
> +import org.springframework.test.context.jdbc.Sql;
Нужно убрать весь не используемый импорт

2022-08-12 19:19 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>                  .collect(Collectors.toSet());
Отличный воркэраунд, но раз работа о базах данных, попробуй это решить не на стримах, а на скл. Например, с использованием order by и лимит. Т.к. если фильмов будет миллион, то вытягивать по сети все фильмы, чтобы найти 2 самых популярных будет накладно

2022-08-12 19:19 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +            jdbcTemplate.update("UPDATE FILMS set RATE = ?, NAME = ?, DESCRIPTION = ?, RELEASE_DATE = ?, DURATION = ?, MPA_ID = ? where ID = ?",
Поправь, пожалуйста, везде  форматирование, чтобы строки были не больше 117 символов

2022-08-12 19:19 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    ).collect(Collectors.toList());
Если я правильно понял что ты хочешь, со строки со 101 по 117, это удалить из FILM_GENRE записи по данному фильму, которых нет в новом в film.genres.id?
Тогда, похоже, этот код можно заменить на "DELETE FROM FILM_GENRE fg
                    WHERE fg.film_id = ? 
                        AND fg.genre_id NOT IN (?)" где  (?) строка film.genres.id через запятую.
Если я правильно угадал мысль, то совет такие отдельные куски логики нужно выводить в отдельный метод, с комментарием. Вообще, если напрашивается комментарий внутри метода, это значит что код нужно выносить в отдельный метод/класс

2022-08-12 19:19 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    film.getGenres().forEach(v -> jdbcTemplate.update("MERGE INTO FILM_GENRE(film_id, genre_id) VALUES ( ?, ? ) ;", film.getId(), v.get("id")));
Похоже тут нужен инсёрт, а не MERGE

2022-08-12 20:05 UTC, VitalyKapustin-git commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    film.getGenres().forEach(v -> jdbcTemplate.update("MERGE INTO FILM_GENRE(film_id, genre_id) VALUES ( ?, ? ) ;", film.getId(), v.get("id")));
Я использовал MERGE так как H2 не воспринимает синтаксис для INSERT с UPDATE на уже существующие записи.

2022-08-12 20:51 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>                  .collect(Collectors.toSet());
Не переделал на sql как я просил.
Плохо в промышленном коде выбирать все фильмы селектом, и потом в джаве сортировать и отбирать последние. Это оптимальнее сделать в sql

2022-08-12 20:51 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    film.getGenres().forEach(v -> jdbcTemplate.update("MERGE INTO FILM_GENRE(film_id, genre_id) VALUES ( ?, ? ) ;", film.getId(), v.get("id")));
Да, тут нужен MERGE, это я ошибся.

2022-08-12 20:57 UTC, ddddemo1984 requested changes

2022-08-12 20:57 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    ).collect(Collectors.toList());
Тогда это код можно заменить одним sql оператором  "DELETE FROM FILM_GENRE fg
WHERE fg.film_id = ?
AND fg.genre_id NOT IN (?)"

2022-08-12 20:57 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>                  .collect(Collectors.toSet());
Не переделал на sql как я просил.
Плохо в промышленном коде выбирать все фильмы селектом, и потом в джаве сортировать и отбирать последние. Это оптимальнее сделать в sql

2022-08-12 21:01 UTC, VitalyKapustin-git commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
>                  .collect(Collectors.toSet());
@ddddemo1984 да, в storage переписал как надо, а в сервисе забыл заменить реализацию. Поправил

2022-08-13 06:13 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    ).collect(Collectors.toList());
Не вижу изменений

2022-08-13 14:28 UTC, VitalyKapustin-git commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    ).collect(Collectors.toList());
@ddddemo1984 поправил. передал массив в качестве arg

2022-08-13 16:44 UTC, ddddemo1984 commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    ).collect(Collectors.toList());
в массив нужно передать жанры в переданном фильме, т.е. film.getGenres(). В этом смысл, чтобы всё сделать в одном sql. Т.е. DELETE удаляет жанры по данному фильму, которых нет в переданном фильме.
И удали лишние импорты

2022-08-13 17:34 UTC, VitalyKapustin-git commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +                    ).collect(Collectors.toList());
@ddddemo1984 done

2022-08-16 12:56 UTC, merged